project/comments/forms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, IntegerField, TextAreaField
from wtforms.validators import Length, DataRequired

class CommentForm(FlaskForm):
    text = TextAreaField('Comment text', validators=[DataRequired(), Length(min=1, max=100)])
    rate = IntegerField('Rate')
    submit = SubmitField('Submit')

project/comments/routes.py
from project import db
from project.comments.forms import CommentForm
from project.models import Product, Comment
from flask import render_template, redirect, url_for, request, Blueprint
from flask_login import current_user, login_required

comments = Blueprint('comments', __name__)

@comments.route('/comment', methods=['POST', 'GET'])
@login_required
def comment():
    form = CommentForm()
    prod_id = request.args.get('prod_id', type=int)
    product = db.session.execute(db.select(Product).where(Product.id == prod_id)).scalars().first()
    if form.validate_on_submit():
        comment = Comment(rate=form.rate.data, text=form.text.data, product=product, author=current_user)
        db.session.add(comment)
        db.session.commit()
        return redirect(url_for('products.catalog'))
    return render_template('comment.html', form=form, product=product, with_navbar=True)

project/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)

@main.route('/')
def main_page():
    return render_template('main_page.html', with_navbar=True)

project/products/routes.py
from project import db
from project.products.forms import AddProductForm, DeleteProductForm
from project.utils import save_image
from project.models import Product
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import current_user, login_required

products = Blueprint('products', __name__)

@products.route('/catalog')
def catalog():
    page = request.args.get('page', 1, type=int)
    products = db.paginate(db.select(Product), per_page=3, page=page)
    product_to_cart = db.session.execute(db.select(Product).where(Product.id == request.args.get('product_id'))).scalars().first()
    if product_to_cart:
        product_to_cart.owner = current_user
        db.session.commit()
    return render_template('catalog.html', products=products, with_navbar=True)


@products.route('/catalog/add', methods=['GET', 'POST'])
@login_required
def add_product():
    if current_user.username == 'admin':
        form = AddProductForm()
        if form.validate_on_submit():
            image_file = save_image(form.image.data, 'products')
            product = Product(title=form.title.data, description=form.description.data, price=form.price.data, image=image_file)
            db.session.add(product)
            db.session.commit()
            flash('New product added successfully!', 'success')
            return redirect(url_for('products.add_product'))
        return render_template('add_product.html', form=form, with_navbar=True)
    else:
        return redirect(url_for('main.main_page'))

@products.route('/catalog/delete', methods=['GET', 'POST'])
@login_required
def delete_product():
    if current_user.username == 'admin':
        form = DeleteProductForm()
        if form.validate_on_submit():
            title = form.title_to_delete.data
            product_to_delete = db.session.execute(db.select(Product).where(Product.title == title)).scalars().first()
            db.session.delete(product_to_delete)
            db.session.commit()
            return redirect(url_for('products.delete_product'))
        return render_template('delete_product.html', form=form, with_navbar=True)
    else:
        return redirect(url_for('main.main_page'))

@products.route('/cart')
@login_required
def cart():
    return render_template('cart.html', with_navbar=True)

project/users/routes.py
from project import db, bcrypt
from project.users.forms import RegistrationForm, LogInForm, UpdateAccountForm
from project.utils import save_image
from project.models import User, Product, Comment
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
import os

users = Blueprint('users', __name__)

@users.route('/reg', methods=['GET', 'POST'])
def registration():
    form = RegistrationForm()
    if form.validate_on_submit():
        username = form.username.data
        password = bcrypt.generate_password_hash(form.password.data)
        email = form.email.data
        db.session.add(User(username=username,  password=password, email=email))
        db.session.commit()
        flash('Account created!', 'success')
        return redirect(url_for('users.log_in'))
    return render_template('registration.html', form=form)

@users.route('/log_in', methods=['GET', 'POST'])
def log_in():
    form = LogInForm()
    if form.validate_on_submit():
        user = db.session.execute(db.select(User).where(User.email == form.email.data)).scalars().first()
        if user and  bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            # next_page exists if user gets redirected
            # trying to get to the profile page being logged out
            next_page = request.args.get('next')
            # user will be forwarded to this next_page authentication
            return redirect(next_page if next_page else url_for('main.main_page')) 
        else:
            flash('Check your email and password.', 'danger')
    return render_template('log_in.html', form=form)

@users.route('/log_out')
def log_out():
    logout_user()
    return redirect(url_for('main.main_page'))

@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.image.data:
            if current_user.image != 'default.jpg':
                os.remove(os.path.join(users.root_path, 'static/profile_pics', current_user.image))
            image_file = save_image(form.image.data, 'profile_pics')
            current_user.image = image_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account was updated successfully!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image)
    return render_template('account.html', image_file=image_file, form=form, with_navbar=True)

project/templates/account.html
{% extends 'template.html' %}
{% block body %}
    <div class="container border p-3 mt-5">
        <div class="row g-4 justify-content-center">
            <div class="col-sm-2">
                <img src="{{ image_file }}" alt="" class="rounded-circle d-block w-100">
            </div>
            <div class="col-6">
                <h1>{{ current_user.username }}</h1>
                <p>Email: {{ current_user.email }}</p>
            </div>
            <div class="w-100"></div>
            {% if current_user.username != 'admin' %}
                <div class="col-8">
                    <!-- TODO make this form collapsed -->
                    <div class="card border-0">
                        <div class="card-title mb-3">
                            <h2>Update account</h2>
                            <hr class="border border-secondary opacity-75">
                        </div>
                        <form method="post" enctype="multipart/form-data">
                            {{ form.csrf_token }}
                            <div class="row g-2">
                                <div class="col-12">
                                    <div class="form-floating">
                                        {% if form.username.errors %}
                                            {{ form.username(class="form-control is-invalid", placeholder="example_name") }}
                                            <div class="invalid-feedback">{{ form.username.errors[0] }}</div>
                                        {% else %}
                                            {{ form.username(class="form-control", placeholder="example_name") }}
                                        {% endif %}
                                        {{ form.username.label }}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="form-floating">
                                        {% if form.email.errors %}
                                            {{ form.email(class="form-control is-invalid", placeholder="example_name") }}
                                            <div class="invalid-feedback">{{ form.email.errors[0] }}</div>
                                        {% else %}
                                            {{ form.email(class="form-control", placeholder="example@mail.com") }}
                                        {% endif %}
                                        {{ form.email.label }}
                                    </div>
                                </div>
                                <div class="col-12">
                                    <div class="mt-3">
                                        {{ form.image.label(class="form-label") }}
                                        {{ form.image(class="form-control", type="file") }}
                                        {% if form.image.errors %}
                                            {% for error in form.image.errors %}
                                                <span class="text-danger">{{ error }}</span><br>
                                            {% endfor %}
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="mt-4 mb-3">
                                {{ form.submit(class="btn btn-primary btn-md w-100") }}
                            </div>
                        </form>
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}

project/templates/add_product.html
{% extends 'template.html' %}
{% block body %}
<div class="container mt-4">
    <div class="card border-0">
        <div class="card-title mb-3">
            <h2>Add product</h2>
            <hr class="border border-secondary opacity-75">
        </div>
        <form method="post" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <div class="row g-2">
                <div class="col-6">
                    <div class="form-floating">
                        {% if form.title.errors %}
                            {{ form.title(class="form-control is-invalid", placeholder="example_title") }}
                            <div class="invalid-feedback">{{ form.title.errors[0] }}</div>
                        {% else %}
                            {{ form.title(class="form-control", placeholder="example_title") }}
                        {% endif %}
                        {{ form.title.label }}
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-floating">
                        {% if form.price.errors %}
                            {{ form.price(class="form-control is-invalid", placeholder="description") }}
                            <div class="invalid-feedback">{{ form.price.errors[0] }}</div>
                        {% else %}
                            {{ form.price(class="form-control", placeholder="description") }} 
                        {% endif %}
                        {{ form.price.label }}
                    </div>
                </div>
                <div class="col-12">
                    <div class="form-floating">
                        {% if form.description.errors %}
                            {{ form.description(class="form-control is-invalid", placeholder="description") }}
                            <div class="invalid-feedback">{{ form.description.errors[0] }}</div>
                        {% else %}
                            {{ form.description(class="form-control", placeholder="description") }}
                        {% endif %}
                        {{ form.description.label }}
                    </div>
                </div>
                <div class="w-100"></div>
                <div class="col-4">
                    <div class="mt-3">
                        {{ form.image.label(class="form-label") }}
                        {{ form.image(class="form-control", type="file") }}
                        {% if form.image.errors %}
                            {% for error in form.image.errors %}
                                <span class="text-danger">{{ error }}</span><br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="mt-4 mb-3">
                {{ form.submit(class="btn btn-primary btn-md w-100") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

project/templates/cart.html
{% extends 'template.html' %}
{% block body %}
<div class="container">
    {% if current_user.products_in_cart %}
        <h2 class="m-4 text-center">Your cart:</h2>
    {% else %}
        <h2 class="m-4 text-center">Your cart is empty</h2>
    {% endif %}

    <div class="vstack gap-3">
        {% for product in current_user.products_in_cart %}
        <div class="card">
            <div class="row g-0">
                <div class="col-md-2">
                    <img src="{{ url_for('static', filename='products/' + product.image) }}" class="img-fluid"
                        alt="epic image">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h3 class="card-title mb-4">{{ product.title }}</h3>
                        <p class="card-text">{{ product.description }}</p>
                        <a href="{{ url_for('comments.comment', prod_id=product.id) }}" class="btn btn-dark">Add comment</a>
                        {% if product.comments %}
                        <button class="btn btn-dark" type="button" data-bs-toggle="collapse"
                            data-bs-target="#commentSection{{ product.id }}" aria-controls="commentSection"> Show
                            comments</button>
                        {% endif %}
                        <div class="collapse mt-1" id="commentSection{{ product.id }}">
                            {% for comment in product.comments %}
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <img class="rounded-circle d-block w-100"
                                                src="{{ url_for('static', filename='profile_pics/' + comment.author.image) }}"
                                                alt="">
                                        </div>
                                        <div class="col">
                                            <h4>{{ comment.author.username }}</h4>
                                        </div>
                                        <div class="col">
                                            <p class="card-text">{{ comment.text }}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <h4>{{ comment.rate }} / 5</h4>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

project/templates/catalog.html
{% extends 'template.html' %}
{% block body %}
<div class="container">
    {% if products.total %}
    <h2 class="m-4 text-center">Pick your favorite!</h2>
    {% else %}
    <h2 class="m-4 text-center">No products today, sorry!</h2>
    {% endif %}

    <div class="vstack gap-3">
        {% for product in products %}
        <div class="card">
            <div class="row g-0">
                <div class="col-md-2">
                    <img src="{{ url_for('static', filename='products/' + product.image) }}" class="img-fluid"
                        alt="epic image">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h3 class="card-title mb-4">{{ product.title }}</h3>
                        <p class="card-text">{{ product.description }}</p>
                        <a href="{{ url_for('comments.comment', prod_id=product.id) }}" class="btn btn-dark">Add comment</a>
                        {% if product.comments %}
                        <button class="btn btn-dark" type="button" data-bs-toggle="collapse"
                            data-bs-target="#commentSection{{ product.id }}" aria-controls="commentSection"> Show
                            comments</button>
                        {% endif %}
                        <div class="collapse mt-1" id="commentSection{{ product.id }}">
                            {% for comment in product.comments %}
                            <div class="card">
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-md-1">
                                            <img class="rounded-circle d-block w-100"
                                                src="{{ url_for('static', filename='profile_pics/' + comment.author.image) }}"
                                                alt="">
                                        </div>
                                        <div class="col-3">
                                            <h4>{{ comment.author.username }}</h4>
                                        </div>
                                        <div class="col">
                                            <p class="card-text">{{ comment.text }}</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-footer">
                                    <h4>{{ comment.rate }} / 5</h4>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="card-footer text-center h-100">
                        <h4 class="card-title mt-5 mb-4">{{ product.price }}</h4>
                        {% if product.user_id %}
                            <a href="{{ url_for('products.catalog', product_id=product.id) }}" class="btn btn-dark btn-lg mb-3 mt-auto w-100 disabled">Add to cart</a>
                        {% else %}
                            <a href="{{ url_for('products.catalog', product_id=product.id) }}" class="btn btn-dark btn-lg mb-3 mt-auto w-100">Add to cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <nav>
        <ul class="pagination pagination-lg justify-content-center mt-3">
            {% for page_num in products.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
            {% if products.page == page_num %}
            <li class="page-item active" aria-current="page">
                {% else %}
            <li class="page-item">
                {% endif %}

                {% if page_num %}
                <a class="page-link mx-1" href="{{ url_for('products.catalog', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                <span class="mx-2" style="font-weight: 700;"> . . . </span>
                {% endif %}
            </li>
            {% endfor %}
        </ul>
    </nav>
</div>
{% endblock %}

project/templates/comment.html
{% extends 'template.html' %}
{% block body %}
<div class="container mt-2">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                    <div class="card-title"><h2>Add a comment</h2></div>
                    <form method="post">
                        {{ form.csrf_token }}
                        {{ form.text(class="form-control") }}
                        {{ form.rate(class="form-range", type="range", min=1, max=5, step=1) }}
                        {{ form.submit(class="btn btn-dark") }}
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-3">
            <div class="card">
                <div class="card-body">
                    <div class="card-title"><h2>{{ product.title }}</h2></div>
                    <img src="{{ url_for('static', filename='products/' + product.image) }}" class="d-block w-100" alt="">
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/templates/delete_product.html
{% extends 'template.html' %}
{% block body %}
<div class="container mt-4">
    <div class="card-title mb-3">
        <h2>Delete product</h2>
        <hr class="border border-secondary opacity-75">
        <form method="post" enctype="multipart/form-data">
            {{ form.csrf_token }}
            <div class="col-12">
                <div class="form-floating">
                    {% if form.title_to_delete.errors %}
                        {{ form.title_to_delete(class="form-control is-invalid", placeholder="example_title_to_delete") }}
                            <div class="invalid-feedback">{{ form.title_to_delete.errors[0] }}</div>
                    {% else %}
                        {{ form.title_to_delete(class="form-control", placeholder="example_title_to_delete") }}
                    {% endif %}
                    {{ form.title_to_delete.label }}
                </div>
            </div>
            <div class="mt-4 mb-3">
                {{ form.delete(class="btn btn-primary btn-md w-100") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

project/templates/log_in.html
{% extends 'template.html' %}
{% block body %}
<div class="card border-secondary position-absolute top-50 start-50 translate-middle p-5">
    <div class="card-title text-center mb-3">
        <h2>Wellcome Back!</h2>
        <hr class="border border-secondary opacity-75">
    </div>
    <form method="post">
        {{ form.csrf_token }}
        <div class="row g-2">
            <div class="col-12">
                <div class="form-floating">
                    {{ form.email(class="form-control", placeholder="example_name") }}
                    {{ form.email.label }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating">
                    {{ form.password(class="form-control", placeholder="password")}}
                    {{ form.password.label }}
                </div>
            </div>
        </div>

        
        <div class="mt-4 mb-3">
            {{ form.log_in(class="btn btn-primary btn-md w-100")}}
        </div>
        <div class="row">
            <div class="col">
                <a href="{{ url_for('users.registration') }}">Don't have an account?</a>
            </div>
            <div class="col">
                <div class="form-check form-check-reverse me-4">
                        {{ form.remember_me(class="form-check-input") }}
                        {{ form.remember_me.label(class="form-check-label") }}
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

project/templates/main_page.html
{% extends 'template.html' %}
{% block body %}
<div id="MainCarousel" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner bg-dark">
        <div class="carousel-indicators mt-1 top-0">
            <button type="button" data-bs-target="#MainCarousel" data-bs-slide-to="0" aria-label="Slide 1" class="active" aria-current="true"></button>
            <button type="button" data-bs-target="#MainCarousel" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#MainCarousel" data-bs-slide-to="2" aria-label="Slide 3"></button>
        </div>
        <div class="carousel-item active">
            <div style="min-height:var(--carousel-height);">
                <img src="{{ url_for('static', filename='carousel_pics/shawarma1.jpg') }}" class="main_car_img d-block w-100" alt="">
                <div class="carousel-caption d-none d-lg-block text-end top-0 mt-5">
                    <h1>Amazing and unique flavours</h1>
                    <p class="mt-3 carousel-p">Try our brand new Nachos shawarma,<br>innovative shawarma and small shawarma</p>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div style="min-height:var(--carousel-height);">
                <img src="{{ url_for('static', filename='carousel_pics/shawarma2.jpg') }}" class="main_car_img d-block w-100" alt="">
                <div class="carousel-caption d-none d-lg-block top-0 mt-2">
                    <h1>Only on our site</h1>
                </div>
            </div>
        </div>
        <div class="carousel-item">
            <div style="min-height:var(--carousel-height);">
                <img src="{{ url_for('static', filename='carousel_pics/shawarma3.jpg') }}" class="main_car_img d-block w-100" alt="">
                <div class="carousel-caption d-none d-lg-block text-start top-0 mt-5">
                    <h1>Unsurpassed classic</h1>
                    <p class="mt-3 carousel-p">Delious shawarma with cheese,<br>short shawarma and shawarma classic</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

project/templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark" style="height:var(--navbar-height);">
    <div class="container-sm">
        <a href="{{ url_for('main.main_page') }}" class="navbar-brand">HOME</a>
        <ul class="navbar-nav me-auto">
            <li class="nav-item">
                <a href="{{ url_for('products.catalog') }}" class="nav-link" aria-current="page">Catalog</a>
            </li>
            {% if current_user.username == 'admin' %}
                <li class="nav-item">
                    <a href="{{ url_for('products.delete_product') }}" class="nav-link">Delete product</a>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('products.add_product') }}" class="nav-link">Add product</a>
                </li>
            {% endif %}
        </ul>
        {% if current_user.is_authenticated %}
            <div class="navbar-nav dropdown">
                <a href="#" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">Account</a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{{ url_for('users.account') }}" class="dropdown-item">Profile page</a>
                        <a href="{{ url_for('products.cart') }}" class="dropdown-item">Cart</a>
                        <a href="{{ url_for('users.log_out') }}" class="dropdown-item">Log Out</a>
                    </li>
                </ul>
            </div>
        {% else %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a href="{{ url_for('users.log_in') }}" class="nav-link">Log In</a>
                </li>
                <li class="nav-item py-1 mx-2">
                    <div class="vr text-white h-100"></div>
                </li>
                <li class="nav-item">
                    <a href="{{ url_for('users.registration') }}" class="nav-link">Sign Up</a>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>

project/templates/registration.html
{% extends "template.html" %}
{% block body %}
<div class="card border-secondary shadow w-25 position-absolute top-50 start-50 translate-middle p-5">
    <div class="card-title text-center mb-3">
        <h2>Join Today!</h2>
        <hr class="border border-secondary opacity-75">
    </div>
    <form method="post">
        {{ form.csrf_token }}
        <div class="row g-2">
            <div class="col-12">
                <div class="form-floating">
                    {% if form.username.errors %}
                        {{ form.username(class="form-control is-invalid", placeholder="example_name") }}
                        <div class="invalid-feedback">{{ form.username.errors[0] }}</div>
                    {% else %}
                        {{ form.username(class="form-control", placeholder="example_name") }}
                    {% endif %}
                    {{ form.username.label }}
                </div>
            </div>
            <div class="col-12">
                <div class="form-floating">
                    {% if form.email.errors %}
                        {{ form.email(class="form-control is-invalid", placeholder="example_name") }}
                        <div class="invalid-feedback">{{ form.email.errors[0] }}</div>
                    {% else %}
                        {{ form.email(class="form-control", placeholder="example@mail.com") }}
                    {% endif %}
                    {{ form.email.label }}
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-floating">
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid", placeholder="example_name") }}
                        <div class="invalid-feedback">{{ form.password.errors[0] }}</div>
                    {% else %}
                        {{ form.password(class="form-control", placeholder="example@mail.com") }}
                    {% endif %}
                    {{ form.password.label }}
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-floating">
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid", placeholder="example_name") }}
                        <div class="invalid-feedback">{{ form.confirm_password.errors[0] }}</div>
                    {% else %}
                        {{ form.confirm_password(class="form-control", placeholder="example@mail.com") }}
                    {% endif %}
                    {{ form.confirm_password.label }}
                </div>
            </div>
        </div>

        <div class="mt-4 mb-3">
            {{ form.submit(class="btn btn-primary btn-md w-100") }}
        </div>


    </form>
</div>
{% endblock %}